name: Update Documentation

on:
  workflow_run:
    workflows: ["Publish Release", "Publish Snapshot"]
    types: [completed]
    branches: [main]

jobs:
  documentation:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Update Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/prepare_javadoc.sh
          git config user.name "Eclipse KeyBot"
          git config user.email "keyple-bot@eclipse.org" 
          git add -A
          git commit -m "docs: update documentation"
          git push